version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    env_file: docker/.env
    entrypoint: /docker/entrypoint.sh
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:16.1-bullseye
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: docker/.env
volumes:
  postgres:
